project_name: karmor

builds:
  - binary: karmor
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags: -w -s -X github.com/kubearmor/kubearmor-client/selfupdate.BuildDate={{.Date}} -X github.com/kubearmor/kubearmor-client/selfupdate.GitSummary={{.Version}}
    env:
      - CGO_ENABLED=0

signs:
  - cmd: cosign
    certificate: '${artifact}.cert'
    args:
      - sign-blob
      - '--output-certificate=${certificate}' 
      - '--output-signature=${signature}'
      - '${artifact}'
      - --yes
    artifacts: all
    output: true
