project_name: karmor

builds:
  - binary: karmor
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags: -w -s -X github.com/kubearmor/kubearmor-client/selfupdate.BuildDate={{.Date}} -X github.com/kubearmor/kubearmor-client/selfupdate.GitSummary={{.Version}}
    env:
      - CGO_ENABLED=0
