services:
  kubearmor:
    cap_add:
    - SETUID
    - SETGID
    - SETPCAP
    - SYS_ADMIN
    - SYS_PTRACE
    - MAC_ADMIN
    - SYS_RESOURCE
    - IPC_LOCK
    - DAC_OVERRIDE
    - DAC_READ_SEARCH
    command:
    - -k8s=false
    {{- if .EnableKubeArmorPolicy }}
    - -enableKubeArmorPolicy
    {{- end }}
    {{- if .EnableKubeArmorHostPolicy }}
    - -enableKubeArmorHostPolicy
    {{- end }}
    - -visibility={{ .Visibility }}
    - -hostVisibility={{ .HostVisibility }}
    - -criSocket=unix:///run/podman/podman.sock
    - -defaultFilePosture={{.DefaultFilePosture}}
    - -defaultNetworkPosture={{.DefaultNetworkPosture}}
    - -defaultCapabilitiesPosture={{.DefaultCapabilitiesPosture}}
    - -hostDefaultFilePosture={{.HostDefaultFilePosture}}
    - -hostDefaultNetworkPosture={{.HostDefaultNetworkPosture}}
    - -hostDefaultCapabilitiesPosture={{.HostDefaultCapabilitiesPosture}}
    container_name: kubearmor
    depends_on:
      kubearmor-init:
        condition: service_completed_successfully
    hostname: cheithanya
    image: docker.io/cheithanya/kubearmor:latest
    labels:
      app: kubearmor
    pid: host
    ports:
    - 32767:32767
    privileged: true
    pull_policy: always
    restart: always
    user: root
    volumes:
    - /tmp:/opt/kubearmor/BPF
    - /sys/fs/bpf:/sys/fs/bpf
    - /sys/kernel/security:/sys/kernel/security
    - /sys/kernel/debug:/sys/kernel/debug
    - /etc/apparmor.d:/etc/apparmor.d
    - /var/run/docker.sock:/var/run/docker.sock
    - /run/docker:/run/docker
    - /var/lib/docker:/var/lib/docker
    - /etc/containers/oci/hooks.d/:/etc/containers/oci/hooks.d/:rw
    - /usr/share/kubearmor:/usr/share/kubearmor:rw
    - /var/run/kubearmor:/var/run/kubearmor:rw

    
  kubearmor-init:
    cap_add:
    - SETUID
    - SETGID
    - SETPCAP
    - SYS_ADMIN
    - SYS_PTRACE
    - MAC_ADMIN
    - SYS_RESOURCE
    - IPC_LOCK
    - DAC_OVERRIDE
    - DAC_READ_SEARCH
    container_name: kubearmor-init
    image: docker.io/cheithanya/kubearmor-init:latest
    labels:
      app: kubearmor-init
    privileged: true
    pull_policy: always
    restart: on-failure
    user: root
    volumes:
    - /tmp:/opt/kubearmor/BPF:rw,z
    - /lib/modules:/lib/modules:ro,z
    - /sys/fs/bpf:/sys/fs/bpf:ro,z
    - /sys/kernel/security:/sys/kernel/security:ro,z
    - /sys/kernel/debug:/sys/kernel/debug:ro,z
    - /usr/src:/usr/src:z
    - /media/root/etc/os-release:/media/root/etc/os-release:ro,z
    - /etc/containers/oci/hooks.d/:/etc/containers/oci/hooks.d/:rw,z
    - /usr/share/kubearmor:/usr/share/kubearmor:rw,z
